;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #2E3440
background-alt = #4C566A
foreground = #d8dee9
primary = #e5e9f0
secondary = #4c566a
alert = #bf616a
disabled = #eceff4

[bar/main]
modules-center = rightpanel i3 leftpanel
modules-right = sep rightpanel pulseaudio leftpanel sep rightpanel date leftpanel sep rightpanel tray leftpanel
separator =
monitor = DP-0

bottom = false
fixed-center = true
padding = 0
padding-right = 1
padding-left = 1
width = 100%
height = 31
offset-x = 0%
offset-y = 0%
radius-top = 0
radius-bottom = 0

background = #00000000
foreground = ${colors.foreground}
dim-value = 1.0

line-size = 2
line-color = ${colors.foreground}

border-top-size = 8
border-top-color = #00000000
border-left-size = 8
border-left-color = #00000000
border-right-size = 8
border-right-color = #00000000

font-0 = "Cantarell:style=Bold;3"
font-1 = "Font Awesome 7 Free Solid:style=Solid;3"
font-2 = "Iosevka Nerd Font:style=Medium:size=18;4"
font-3 = "Iosevka Nerd Font:size=14;3"

enable-ipc = true

[bar/side]
modules-left = rightpanel archlogo leftpanel sep rightpanel weather leftpanel sep 
modules-center = rightpanel i3 leftpanel
separator =
monitor = DP-2

bottom = false
fixed-center = true
padding = 0
padding-right = 1
padding-left = 1
width = 100%
height = 30
offset-x = 0%
offset-y = 0%
radius-top = 0
radius-bottom = 0

background = #00000000
foreground = ${colors.foreground}
dim-value = 1.0

line-size = 2
line-color = ${colors.foreground}

border-top-size = 8
border-top-color = #00000000
border-left-size = 8
border-left-color = #00000000
border-right-size = 8
border-right-color = #00000000

font-0 = "Cantarell:style=Bold;3"
font-1 = "Font Awesome 7 Free Solid:style=Solid;3"
font-2 = "Iosevka Nerd Font:style=Medium:size=18;4"
font-3 = "Iosevka Nerd Font:size=14;3"

enable-ipc = true

[module/sep]
type = custom/text
format = " "

[module/archlogo]
type = custom/text
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format = "%{T4}"

[module/leftpanel]
type = custom/text
format-background = #00000000
format-foreground = ${colors.background}
format = "%{T3}"

[module/rightpanel]
type = custom/text
format-background = #00000000
format-foreground = ${colors.background}
format = "%{T3}"
format-font = 2

[module/i3]
type = internal/i3
pin-workspaces = true
show-urgent = true
strip-wsnumbers = true
index-sort = true
enable-click = true
enable-scroll = true
wrapping-scroll = false
reverse-scroll = true
fuzzy-match = true

ws-icon-0 = 1;%{T2}
ws-icon-1 = 2;%{T2}
ws-icon-2 = 3;%{T2}
ws-icon-3 = 4;%{T2}
ws-icon-4 = 5;%{T2}
ws-icon-5 = 6;%{T2}
ws-icon-6 = 7;%{T2}
ws-icon-7 = 8;%{T2}
ws-icon-8 = 9;%{T2}
ws-icon-9 = 10;%{T2}
ws-icon-10 = 11;%{T2}
ws-icon-11 = 12;%{T2}

format = <label-state>

label-focused = %icon%
label-focused-foreground = ${colors.foreground}
label-focused-background = ${colors.background}
label-focused-underline = ${colors.foreground}
label-focused-padding = 1

label-unfocused = %icon%
label-unfocused-foreground = ${colors.secondary}
label-unfocused-background = ${colors.background}
label-unfocused-padding = 1

label-visible = %icon%
label-visible-underline = ${colors.secondary}
label-visible-foreground = ${colors.secondary}
label-visible-background = ${colors.background}
label-visible-padding = 1

label-urgent = %icon%
label-urgent-foreground = ${colors.alert}
label-urgent-background = ${colors.background}
label-urgent-padding = 1

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false
interval = 5

format-volume = <label-volume>

label-muted = "%{T2}"
label-muted-foreground = ${colors.alert}
label-muted-background = ${colors.background}

label-volume = "%{T2} %{T1}%percentage%%"
label-volume-foreground = ${colors.foreground}
label-volume-background = ${colors.background}

; [module/battery]
; type = internal/battery
; full-at = 99
; low-at = 5
; battery = BAT1
; adapter = ADP1
; label-charging = "  %percentage%% "
; label-discharging = "  %percentage%% "
; label-full = "  %percentage%% "
; label-low = "  %percentage%%"
; label-charging-background = ${colors.background}
; label-discharging-background = ${colors.background}
; label-full-background = ${colors.background}
; label-low-background = ${colors.background}
; poll-interval = 5

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S

label = "%{T2} %{T1}%date%"
label-foreground = ${colors.primary}
label-background = ${colors.background}

[module/weather]
type = custom/script
exec = ~/.config/polybar/weather.sh
interval = 600

format-background = ${colors.background}
format-foreground = ${colors.foreground}

[module/tray]
type = internal/tray

tray-spacing = 5px

tray-background = ${colors.background}
tray-foreground = ${colors.background}
format-background = ${colors.background}

[settings]
screenchange-reload = true

pseudo-transparency = true
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-border = over
